language: perl

install:
  - cpanm -n Log::Log4perl
  - cpanm -n Test::Builder::Module

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script: HARNESS_IS_VERBOSE=1 prove -lv t xt
